spring:
  application:
    name: payment-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/affablebean
    username: root
    password: 308810
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8090

